name: Documentation Update📄
description: Suggest how we can improve our documentation
title: "Documentation📄: "
labels: [documentation]


body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Documentation update report
  - type: textarea
    attributes:
      label: What is the current documentation state?
      description: "Copy and paste the text currently in the documentation. If you want to improve graphs or photos, please provide a screenshot of the original."
  - type: textarea
    attributes:
      label: Where is it located?
      description: "Provide additional information about the location where you have copied the above statement from."
  - type: textarea
    attributes:
      label: Please provie the reason to improve the part of the document?
      description: "Please explain why the statement needs to be updated. This can be because it is confusing, incorrect, spelling/grammatical errors, etc."
  - type: textarea
    attributes:
      label: Proposed Changes
      description: "Please propose how you would rewrite the statement. If you have a precise proposal, please make the changes and open a pull request."
  - type: textarea
    attributes:
      label: Additional context.
      description: "Add any other context or useful information about the documentation update here."
